---
- name: install BEAGLE RPM
  yum: pkg=https://s3.amazonaws.com/startreerenaissance/rpm/beagle_2.1.x86_64.rpm

- name: install samtools
  yum: pkg=http://dl.fedoraproject.org/pub/epel/6/x86_64/samtools-0.1.18-2.el6.x86_64.rpm

- name: Add /usr/local/lib to java.library.path in SPARK
  lineinfile: >
    dest=/root/spark/conf/spark-env.sh
    line="export SPARK_LIBRARY_PATH=/usr/local/lib:/root/hadoop-native:$SPARK_LIBRARY_PATH"
    regexp="^export SPARK_LIBRARY_PATH="
    create=False
    insertafter=EOF
    state=present
    owner=root
  notify:
    - stop spark
    - start spark

- name: Install some useful packages
  yum: pkg={{item}} state=installed
  with_items:
    - tree
    - htop
    - tmux

- name: Install ack
  get_url: >
    url=http://beyondgrep.com/ack-2.12-single-file
    dest=/usr/bin/ack
    owner=root
    group=root
    mode=0755

- name: Install tmux config
  copy: src=tmux.conf dest=/root/.tmux.conf

- name: Template out sudoer no tty
  template: >
    src=ec2-user-notty.j2
    dest=/etc/sudoers.d/ec2-user-notty
    mode=440
    owner=root
    group=root

