---
- name: stop spark
  command: "/root/spark/bin/stop-all.sh"
  when: ec2_tag_spark_node_type == 'master'

- name: start spark
  command: "/root/spark/bin/start-all.sh"
  when: ec2_tag_spark_node_type == 'master'
