---
- name: install BEAGLE RPM
  yum: pkg=https://s3.amazonaws.com/startreerenaissance/rpm/beagle_2.1.x86_64.rpm
  when: ec2_master_group_name in ec2_security_group_names or ec2_slave_group_name in ec2_security_group_names

- name: Add /usr/local/lib to java.library.path in SPARK
  lineinfile: dest=/root/spark/conf/spark-env.sh
              line="export SPARK_LIBRARY_PATH=/usr/local/lib:$SPARK_LIBRARY_PATH"
              regexp="^export SPARK_LIBRARY_PATH=/usr/local/lib:"
              create=False
              insertafter=EOF
              state=present
              owner=root
  when: ec2_master_group_name in ec2_security_group_names or ec2_slave_group_name in ec2_security_group_names
  notify:
    - stop spark
    - start spark
