---

- name: Install BEAGLE RPM
  #remote_user: ec2-user
  #sudo: yes
  yum: pkg=https://s3.amazonaws.com/startreerenaissance/rpm/beagle_2.1.x86_64.rpm
  when: ec2_master_group_name in ec2_security_group_names or ec2_slave_group_name in ec2_security_group_names
